version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/api"
      - "/apps/cron"
      - "/apps/invoice"
      - "/apps/og"
      - "/apps/web"
      - "/packages/abis"
      - "/packages/config"
      - "/packages/contracts"
      - "/packages/data"
      - "/packages/db"
      - "/packages/helpers"
      - "/packages/icons"
      - "/packages/image-cropper"
      - "/packages/lens"
      - "/packages/types"
      - "/packages/ui"
    schedule:
      interval: "daily"
