version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"

  # Apps
  - package-ecosystem: "npm"
    directory: "apps/web"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "apps/api"
    target-branch: "main"
    schedule:
      interval: "daily"

  # Packages
  - package-ecosystem: "npm"
    directory: "packages/abis"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/data"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/eslint-config-weblint"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/lens"
    target-branch: "main"
    schedule:
      interval: "daily"
