image: node:18

cache:
  paths:
    - node_modules/
    - .next/cache/

stages:
  - build
  - test
  - clean

before_script:
  - node -v
  - npm -v
  - cp .env.example .env
  - npm ci

lint:
  stage: build
  script:
    - npm run lint

prettier:
  stage: build
  script:
    - npm run prettier:check

codegen:
  stage: build
  script:
    - npm run codegen

typecheck:
  stage: build
  script:
    - npm run codegen
    - npm run typecheck

test:
  image: cypress/browsers:node16.13.2-chrome100-ff98
  stage: test
  before_script: []
  allow_failure: true
  script:
    - npm ci
    - npm run cypress:e2e

housekeeping:
  stage: clean
  before_script: []
  script:
    - curl --request POST --header "PRIVATE-TOKEN:$ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/housekeeping
  only:
    - main

clean-branches:
  stage: clean
  before_script: []
  script:
    - curl --request DELETE --header "PRIVATE-TOKEN:$ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/repository/merged_branches
  only:
    - main
