name = "staff-picks"
main = "src/index.ts"
compatibility_date = "2023-01-25"
keep_vars = true
node_compat = true

routes = [
	{ pattern = "staff-picks.hey.xyz", custom_domain = true }
]

[env.production.vars]
RELEASE = ""
SUPABASE_KEY = ""
