name: DB Migrate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  db-migrate:
    name: DB Migrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸšª
        uses: actions/checkout@v4

      - name: Setup pnpm ğŸŒ¸
        uses: pnpm/action-setup@v2.2.4

      - name: Setup node ğŸ€
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies ğŸ“¦
        working-directory: ./apps/api
        run: pnpm i

      - name: Migrate Staging ğŸš€
        working-directory: ./apps/api
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: pnpm prisma:migrate

      - name: Migrate Testnet ğŸš€
        working-directory: ./apps/api
        env:
          DATABASE_URL: ${{ secrets.TESTNET_DATABASE_URL }}
        run: pnpm prisma:migrate

      - name: Migrate Mainnet ğŸš€
        working-directory: ./apps/api
        env:
          DATABASE_URL: ${{ secrets.MAINNET_DATABASE_URL }}
        run: pnpm prisma:migrate
