name: Deploy cloudflare workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸšª
        uses: actions/checkout@v3

      - name: Check for changes ğŸ“
        id: check
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changed:
              - 'packages/workers/**'

      - name: Cancel if no changes ğŸš«
        id: cancel
        if: steps.check.outputs.changed == 'false'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            console.log('Cancelling...')
            const run_id = "${{ github.run_id }}"
            await github.actions.cancelWorkflowRun({ owner, repo, run_id })
            return 'stop'

      - name: Waiting for cancellation
        if: ${{ steps.cancel.outputs.result == 'stop' }}
        run: |
          sleep 60

      - name: Setup pnpm ğŸŒ¸
        uses: pnpm/action-setup@v2.2.4

      - name: Setup node ğŸ€
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install ğŸ“¦
        run: pnpm install --frozen-lockfile

      - name: Deploy ğŸš€
        run: |
          pnpm add wrangler -g
          pnpm workers:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
