name: i18n extract

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  extract:
    name: i18n extract
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸšª
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BIGINT_GH_TOKEN }}

      - name: Setup bun ğŸŒ¸
        uses: bun/action-setup@v2.2.4

      - name: Setup node ğŸ€
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'bun'

      - name: Install dependencies and extract i18n ğŸ“¦
        run: |
          bun install --frozen-lockfile
          bun i18n:extract

      - name: Commit & Push changes ğŸ“¤
        uses: actions-js/push@master
        with:
          message: 'chore(cron): i18n extract'
          github_token: ${{ secrets.BIGINT_GH_TOKEN }}
