name: Sync Testnet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  pull-request:
    name: Open PR to testnet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: Sync Testnet
      with:
        destination_branch: "testnet"
        pr_title: "ğŸ” Sync `testnet` with `main`"
        pr_body: "**ğŸ” Sync `testnet` with `main`**"
        pr_reviewer: "bigint"
        github_token: ${{ secrets.GITHUB_TOKEN }}
