name: Sync Cron Jobs

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  delete-publications-clickhouse:
    name: Delete duplicate publications from Clickhouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸšª
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js, pnpm and dependencies ðŸŒ¸
        uses: ./.github/actions/setup-pnpm

      - name: Delete duplicate publications from Clickhouse
        env:
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
        run: |
          cd packages/cron
          {
            echo "CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}"
          } > .env
          pnpm delete-publications-clickhouse

  replicate-publications-clickhouse:
    name: Replicate publications to Clickhouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸšª
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js, pnpm and dependencies ðŸŒ¸
        uses: ./.github/actions/setup-pnpm

      - name: Replicate publications to Clickhouse
        env:
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
          LENS_DATABASE_URL: ${{ secrets.LENS_DATABASE_URL }}
        run: |
          cd packages/cron
          {
            echo "CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}"
            echo "LENS_DATABASE_URL=${LENS_DATABASE_URL}"
          } > .env
          pnpm replicate-publications-clickhouse
