name: Test

env:
  REDIS_URL: ${{ secrets.REDIS_URL }}
  DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flush-redis:
    name: Flush Redis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸšª
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js, pnpm and dependencies ðŸŒ¸
        uses: ./.github/actions/setup-pnpm

      - name: Flush Redis ðŸ§¹
        working-directory: ./packages/db
        run: pnpm redis:flush
