name: Verify Profiles

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  verify:
    name: Verify Profiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸšª
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node ğŸ€
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Run script ğŸ“œ
        run: node packages/data/verify-profiles.js

      - name: Commit & Push changes ğŸ“¤
        uses: actions-js/push@master
        with:
          message: 'chore(cron): verify profiles'
          author_email: '69431456+bigint@users.noreply.github.com'
          github_token: ${{ secrets.BIGINT_GH_TOKEN }}
          force: true
